repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus]
- repo: https://github.com/python/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==22.1.11]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.1.0]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    files: ^src/apispec_webframeworks/
    additional_dependencies: ["Flask==2.0.1", "tornado", "bottle", "apispec[yaml]>=5.2.1", types-setuptools]
